### ISSUE TITLE
versionCode not in sync

### ISSUE THREAD

**Issue by IzzySoft** [CrazyBytesVE/QS-Modded#1]
Could you please update `module.prop` so it reflects the `versionCode` communicated by `update.json`? Currently, `update.json` says `versionCode: 10` would be available, while `module.prop` (also the one included in the ZIP) still have `versionCode: 1`, which causes an "eternal update cycle" as on each check there seems to be an update available.

Thanks in advance!

**Comment by CrazyBytesVE** [comment]
> Could you please update `module.prop` so it reflects the `versionCode` communicated by `update.json`? Currently, `update.json` says `versionCode: 10` would be available, while `module.prop` (also the one included in the ZIP) still have `versionCode: 1`, which causes an "eternal update cycle" as on each check there seems to be an update available.
> 
> Thanks in advance!

Sorry for the delay. The module is already updated with its respective correction.

**Comment by IzzySoft** [comment]
Unfortunately there's one more error in `update.json`:

```json
  "zipUrl": "https://github.com/CrazyBytesVE/QS-Modded/releases/download/V1.1/QS_Modded.zip",
```

That URL gives a 404, it must me `QS-Modded.zip` (a "minus", not an underscore). Can you please fix that, too? Thanks!

**Comment by CrazyBytesVE** [comment]
> Unfortunately there's one more error in `update.json`:
> 
> ```json
>   "zipUrl": "https://github.com/CrazyBytesVE/QS-Modded/releases/download/V1.1/QS_Modded.zip",
> ```
> 
> That URL gives a 404, it must be `QS-Modded.zip` (a "minus", not an underscore). Can you please fix that, too? Thanks!

Fixed now. Thanks!

**Comment by IzzySoft** [comment]
Update now live in [my Magisk repo](https://apt.izzysoft.de/magisk) :smiley: Thanks!
